# Generated by Django 4.0.1 on 2022-01-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptno', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=14, null=True)),
                ('loc', models.CharField(max_length=13, null=True)),
            ],
            options={
                'db_table': 'dept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('empno', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=10, null=True)),
                ('job', models.CharField(max_length=9, null=True)),
                ('mgr', models.IntegerField(null=True)),
                ('hiredate', models.DateTimeField(null=True)),
                ('sal', models.IntegerField(null=True)),
                ('comm', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'emp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jejuolle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=20)),
                ('distance', models.FloatField()),
                ('time_info', models.CharField(max_length=10)),
                ('start_end_info', models.CharField(max_length=30)),
                ('cre_date', models.DateField()),
            ],
            options={
                'db_table': 'jeju_olle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'owner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('tel', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'playground',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100, null=True)),
                ('shop_desc', models.CharField(max_length=100, null=True)),
                ('rest_date', models.CharField(max_length=100, null=True)),
                ('parking_info', models.CharField(max_length=100, null=True)),
                ('img_path', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'shop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_nm', models.CharField(max_length=50, null=True)),
                ('period', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'warranty',
                'managed': False,
            },
        ),
    ]
